// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPCgtxuZa4wI50cY3z_TptvkxEoalDmkA',
    appId: '1:577909850842:web:67e1e610ed475b07595be3',
    messagingSenderId: '577909850842',
    projectId: 'top-bantz-db7af',
    authDomain: 'top-bantz-db7af.firebaseapp.com',
    databaseURL: 'https://top-bantz-db7af-default-rtdb.firebaseio.com',
    storageBucket: 'top-bantz-db7af.appspot.com',
    measurementId: 'G-YWWRR4BY5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9BbyuytoCbp15jlpRnPvARffV9TL0-s4',
    appId: '1:577909850842:android:11736f0210c09f09595be3',
    messagingSenderId: '577909850842',
    projectId: 'top-bantz-db7af',
    databaseURL: 'https://top-bantz-db7af-default-rtdb.firebaseio.com',
    storageBucket: 'top-bantz-db7af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLwgMmaVDGPcBwmueokmkeS38wuqeRB7o',
    appId: '1:577909850842:ios:c14e034f2f3996c3595be3',
    messagingSenderId: '577909850842',
    projectId: 'top-bantz-db7af',
    databaseURL: 'https://top-bantz-db7af-default-rtdb.firebaseio.com',
    storageBucket: 'top-bantz-db7af.appspot.com',
    androidClientId: '577909850842-prv1cfneaofvml77cj1tq4t13avfbchq.apps.googleusercontent.com',
    iosClientId: '577909850842-b6kvbjlfa838tglaugdl6ol462sjs28g.apps.googleusercontent.com',
    iosBundleId: 'com.example.topBantz2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLwgMmaVDGPcBwmueokmkeS38wuqeRB7o',
    appId: '1:577909850842:ios:c14e034f2f3996c3595be3',
    messagingSenderId: '577909850842',
    projectId: 'top-bantz-db7af',
    databaseURL: 'https://top-bantz-db7af-default-rtdb.firebaseio.com',
    storageBucket: 'top-bantz-db7af.appspot.com',
    androidClientId: '577909850842-prv1cfneaofvml77cj1tq4t13avfbchq.apps.googleusercontent.com',
    iosClientId: '577909850842-b6kvbjlfa838tglaugdl6ol462sjs28g.apps.googleusercontent.com',
    iosBundleId: 'com.example.topBantz2',
  );
}
